version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python ./mysite/manage.py runserver 0.0.0.0:8000 --settings=mysite.settings.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
