version: '3'

services:
  db:
    image: postgres:9.3

  web:
    image: django_app
    command: python ./mysite/manage.py runserver 0.0.0.0:8000 --settings=mysite.settings.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - seed
      - db
    restart: on-failure

  seed:
    image: django_app
    command: python ./mysite/manage.py seed stats --number=100 --settings=mysite.settings.dev
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - migration
      - db
    restart: on-failure

  migration:
    build: .
    image: django_app
    command: ["./wait-for-it.sh", "db:5432", "--", "bash", "./migrate-models.sh"]
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
    restart: on-failure
