# Generated by Django 2.0.2 on 2019-01-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank_Total_Commits_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('login', models.CharField(max_length=100)),
                ('contributions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rank_Unique_Commits_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('login', models.CharField(max_length=100)),
                ('contributions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Total_Commits_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('repo', models.CharField(default='github', max_length=150)),
                ('url', models.CharField(default='github', max_length=150)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
