# Generated by Django 2.0.2 on 2018-12-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Old_User',
            new_name='Total_Commits_User',
        ),
        migrations.RenameModel(
            old_name='New_User',
            new_name='Unique_Commits_User',
        ),
    ]
