# Generated by Django 2.0.2 on 2019-01-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unique_Commits_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(default='github', max_length=150)),
                ('url', models.CharField(default='github', max_length=150)),
                ('created_at', models.DateTimeField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Login_User')),
            ],
        ),
        migrations.DeleteModel(
            name='Total_Commits_User',
        ),
        migrations.RemoveField(
            model_name='rank_total_commits_users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rank_unique_commits_users',
            name='id',
        ),
        migrations.AlterField(
            model_name='rank_total_commits_users',
            name='rank',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rank_unique_commits_users',
            name='rank',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
