// ACTION TYPES
export const FETCH_ORIGINAL_LIST = 'FETCH_ORIGINAL_LIST';
export const FETCH_ORIGINAL_LIST_ERROR = 'FETCH_ORIGINAL_LIST_ERROR';
export const FETCH_ORIGINAL_LIST_SUCCESS = 'FETCH_ORIGINAL_LIST_SUCCESS';
export const FETCH_UPDATED_LIST = 'FETCH_UPDATED_LIST';
export const FETCH_UPDATED_LIST_ERROR = 'FETCH_UPDATED_LIST_ERROR';
export const FETCH_UPDATED_LIST_SUCCESS = 'FETCH_UPDATED_LIST_SUCCESS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_ERROR = 'SEARCH_USERS_ERROR';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';

// STRING CONSTANTS
export const NO_RESULTS_LABEL = 'No results';
export const ORIGINAL_RESULTS_LABEL = 'Total commits';
export const UPDATED_RESULTS_LABEL = 'Unique merged PRs';