export const FETCH_ORIGINAL_LIST = 'FETCH_ORIGINAL_LIST';
export const FETCH_ORIGINAL_LIST_ERROR = 'FETCH_ORIGINAL_LIST_ERROR';
export const FETCH_ORIGINAL_LIST_SUCCESS = 'FETCH_ORIGINAL_LIST_SUCCESS';
export const FETCH_UPDATED_LIST = 'FETCH_UPDATED_LIST';
export const FETCH_UPDATED_LIST_ERROR = 'FETCH_UPDATED_LIST_ERROR';
export const FETCH_UPDATED_LIST_SUCCESS = 'FETCH_UPDATED_LIST_SUCCESS';
export const GET_UPDATED_LIST = 'GET_UPDATED_LIST';
export const GET_ORIGINAL_LIST = 'GET_ORIGINAL_LIST';
